# Generated by Django 3.2.15 on 2022-11-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
