# Generated by Django 3.2.15 on 2022-11-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('new_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_log.new_title')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
